name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: get_avr-gcc
      run: sudo apt-get install gcc-avr binutils-avr avr-libc
    - name: compile
      run: make -C 3_Implementation

